version: "3.9"

services:
  webclient:
    build: ./web-client
    hostname: webclienthost
    ports:
      - 8082:8080
    depends_on:
      - redis
      - server
  webfluxclient:
    build: ./webflux-client
    hostname: webfluxclienthost
    ports:
      - 8081:8080
    depends_on:
      - redis
      - server
  server:
    build: ./backend
    hostname: backendhost
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    hostname: redishost
    ports:
      - 6379:6379